export const GET_DISCOUNT_COURSES="GET_DISCOUNT_COURSES";
export const GET_POPULAR_COURSES="GET_POPULAR_COURSES";
export const GET_ID_COURSE="GET_ID_COURSE";
export const GET_CATEGORY_COURSES="GET_CATEGORY_COURSE";
export const GET_INSTRUCTORS_COURSES="GET_INSTRUCTORS_COURSES";